name: Build LaTeX (XeLaTeX)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          engine: xelatex
          root_file: resume.tex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
